/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_jwt;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import javax.crypto.SecretKey;


public class App {
    private boolean verifyJWT(String token){
        try {
            String secretString=System.getenv("VONAGE_API_SIGNATURE_SECRET"); 
            SecretKey key = Keys.hmacShaKeyFor(secretString.getBytes());  
            System.out.println(key);
            Jwts.parser()
                .verifyWith(key)
                .build()
                .parseSignedClaims(token);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            return false;
        }
        return true;
    }
    public String getGreeting() {
        String token1 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c";
        String token2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c";
        System.out.println(verifyJWT(token1));
        System.out.println(verifyJWT(token2));
        return "Hello World 123!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
